db:
  username: ${username.value:postgres}
  password: pass
  pool:
    size: 12
    timeout: 10
  properties:
    first: 123
    second: 567
    third.value: Third
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
spring.profiles.active: qa

logging:
  #  file:
  #    name: project.log
  #    path: /
  level:
    root: INFO
    org.springframework.jdbc.core: TRACE

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://46.249.19.112:5432/spring_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB